application: websec-blog
version: live
runtime: python27
threadsafe: true
api_version: 1


builtins:
- remote_api: on


libraries:
- name: django
  version: "1.2"

- name: jinja2
  version: "latest"


handlers:
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.application
  login: admin

- url: /admin/.*
  script: admin_handlers.app
  login: admin
  secure: always

- url: /static/([^/]+)/(.*)
  static_files: themes/\1/static/\2
  upload: themes/[^/]+/static/.*

- url: /.*
  script: main_handlers.app


env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'


skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 )$
